"""empty message

Revision ID: 3f016704581b
Revises: 
Create Date: 2025-02-09 01:22:39.830684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f016704581b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hydration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('water_intake', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symptom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('workout_type', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('dob',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('weight',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('service',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=60),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('service',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('dob',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    op.drop_table('workout')
    op.drop_table('symptom')
    op.drop_table('period')
    op.drop_table('hydration')
    # ### end Alembic commands ###
